### ISSUE TITLE
Would you be open to accepting a PR for Canada address support?

### ISSUE THREAD

**Issue by ArthurG** [moneals/addresser#2]
Repo looks awesome, and I need Canada support for my use case. 

Would be happy to contribute back Canada address support @moneals  you're interested

**Comment by moneals** [comment]
Hi ArtherG - that would be great. I would be happy to add you as a contributor if you would like to implement support for Canadian addresses.

**Comment by moneals** [comment]
Sorry for the delay on your PR ArthurG - I just merged it.
