### ISSUE TITLE
Not able to parse valid US addresses

### ISSUE THREAD

**Issue by AntonAI** [moneals/addresser#22]
Please see some examples of valid addresses that this library is not able to parse below. 

These have been verified as actual physical addresses that do exist, so it's not a formatting error on the input side:

- 1300 Providence Ridge Turn, North Chesterfield, VA 23236 ("Too many address lines" error)
- 5210 Castlewood Rd Apt E, North Chesterfield, VA 23234 ("Too many address lines" error)
- 2505 Pocoshock Pl Ste 103, North Chesterfield, VA 23235  ("Too many address lines" error)
- 186 N Harrisburg St Apt 3, Oberlin, PA 17113  ("Too many address lines" error)
- 400 Franklin St Apt 205, West Reading, PA 19611  ("Too many address lines" error)
- 315 Salem St Apt A, West Pittston, PA 18643  ("Too many address lines" error)
- 485 State St Apt B, Steelton, PA 17113  ("Too many address lines" error)
- 67A Alameda De Las Pulgas, Redwood City, CA 94062 ("Invalid street address data" error)

**Comment by AntonAI** [comment]
Additional addresses this package is not able to parse:

- 11 Bristol St Apt 2, East Cambridge, MA 02141 ("Too many address lines" error)

**Comment by AntonAI** [comment]
Suspected additional cities where this package is not able to parse addresses:

- North Plainfield, NJ
- Spring Lake Park, MN
- Winchester, CT
- North Miami, FL
- South Tucson, AZ
- East Palo Alto, CA
- North Westport, MA
- South Attleboro, MA
- East Dundee, IL
- West Pleasant View, CO

**Comment by moneals** [comment]
Fixed in 1.1.20
